// <auto-generated />
using System;
using System.Text.Json;
using Festival.Ms.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Festival.Ms.DAL.Migrations
{
    [DbContext(typeof(FestivalContext))]
    [Migration("20240808145525_20240808")]
    partial class _20240808
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Festival.Ms.DAL.EntityConfig.AnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("Festival.Ms.DAL.Interfaces.Entities.CompanyBuysEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cant")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdParticipation")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProduct")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CompanyBusy");
                });

            modelBuilder.Entity("Festival.Ms.DAL.Interfaces.Entities.CompanyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<long>("IdUserAuth")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user_auth");

                    b.HasKey("Id")
                        .HasName("companies_pk");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_IdCompany");

                    b.HasIndex("IdUserAuth")
                        .HasDatabaseName("IX_id_user_auth");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("Festival.Ms.DAL.Interfaces.Entities.CompanySalesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cant")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdParticipation")
                        .HasColumnType("bigint");

                    b.Property<long>("IdProduct")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CompanySale");
                });

            modelBuilder.Entity("Festival.Ms.DAL.Interfaces.Entities.DeviceParticipationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("Hash");

                    b.Property<long>("IdParticipation")
                        .HasColumnType("bigint")
                        .HasColumnName("IdParticipation");

                    b.HasKey("Id")
                        .HasName("PK_DeviceParticipation");

                    b.HasIndex("Hash", "IdParticipation")
                        .IsUnique()
                        .HasDatabaseName("unique_device_hash");

                    b.ToTable("DeviceParticipation", (string)null);
                });

            modelBuilder.Entity("Festival.Ms.DAL.Interfaces.Entities.FestivalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<JsonElement>("Question")
                        .HasColumnType("jsonb")
                        .HasColumnName("question");

                    b.HasKey("Id")
                        .HasName("PK_festival");

                    b.HasIndex("Question", "Id")
                        .HasDatabaseName("IX_Festival_Question");

                    b.ToTable("festival", (string)null);
                });

            modelBuilder.Entity("Festival.Ms.DAL.Interfaces.Entities.JuryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("IdUserAuth")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Jury");
                });

            modelBuilder.Entity("Festival.Ms.DAL.Interfaces.Entities.ParticipationCompanyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("IdCompany")
                        .HasColumnType("bigint")
                        .HasColumnName("IdCompany");

                    b.Property<long>("IdFestival")
                        .HasColumnType("bigint")
                        .HasColumnName("IdFestival");

                    b.HasKey("Id")
                        .HasName("participation_company_pk");

                    b.HasIndex("IdCompany", "IdFestival")
                        .IsUnique()
                        .HasDatabaseName("unique_company_festival");

                    b.HasIndex("IdCompany", "IdFestival", "Id")
                        .HasDatabaseName("IX_company_participation");

                    b.ToTable("ParticipationCompany", (string)null);
                });

            modelBuilder.Entity("Festival.Ms.DAL.Interfaces.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Type")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Festival.Ms.DAL.Interfaces.Entities.QuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("Festival.Ms.DAL.Interfaces.Entities.VoteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<long>("IdAnswer")
                        .HasColumnType("bigint")
                        .HasColumnName("id_answer");

                    b.Property<long>("IdParticipationCompany")
                        .HasColumnType("bigint")
                        .HasColumnName("id_participation_company");

                    b.Property<long>("IdQuestion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_question");

                    b.HasKey("Id")
                        .HasName("votes_pk");

                    b.HasIndex("IdAnswer", "IdQuestion", "IdParticipationCompany")
                        .HasDatabaseName("IX_vote");

                    b.ToTable("vote", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
